{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "production-platform.fullname" . }}-mongodb
  labels:
    {{- include "production-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  clusterIP: None
  ports:
    - name: mongo
      port: 27017
      targetPort: mongo
  selector:
    {{- include "production-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "production-platform.fullname" . }}-mongodb
  labels:
    {{- include "production-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  serviceName: {{ include "production-platform.fullname" . }}-mongodb
  replicas: 1
  selector:
    matchLabels:
      {{- include "production-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mongodb
  template:
    metadata:
      labels:
        {{- include "production-platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mongodb
    spec:
      securityContext:
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image }}
          ports:
            - name: mongo
              containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "production-platform.fullname" . }}-secrets
                  key: MONGO_INITDB_ROOT_PASSWORD
          livenessProbe:
            tcpSocket:
              port: mongo
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: mongo
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.mongodb.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if .Values.mongodb.storageClassName }}
        storageClassName: {{ .Values.mongodb.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.mongodb.storage }}
{{- end }}
