apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "production-platform.fullname" . }}
  labels:
    {{- include "production-platform.labels" . | nindent 4 }}
automountServiceAccountToken: false
