global:
  imagePullPolicy: IfNotPresent

services:
  frontend:
    repository: kmc173/production-platform
    tag: frontend-1.0.1
  backend:
    repository: kmc173/production-platform
    tag: backend-1.0.1
  auth:
    repository: kmc173/production-platform
    tag: auth-1.0.1
  notification:
    repository: kmc173/production-platform
    tag: notification-1.0.1

ingress:
  tls:
    enabled: false
